<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConcelhosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 1, 'nome' => 'Águeda']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 2, 'nome' => 'Aljustrel']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 3, 'nome' => 'Amares']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 4, 'nome' => 'Alfândega da Fé']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 5, 'nome' => 'Belmonte']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 6, 'nome' => 'Arganil']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 7, 'nome' => 'Alandroal']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 8, 'nome' => 'Albufeira']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 9, 'nome' => 'Aguiar da Beira']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 10, 'nome' => 'Alcobaça']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 11, 'nome' => 'Alenquer']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 12, 'nome' => 'Alter do Chão']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 13, 'nome' => 'Amarante']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 14, 'nome' => 'Abrantes']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 15, 'nome' => 'Alcácer do Sal']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 16, 'nome' => 'Arcos de Valdevez']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 17, 'nome' => 'Alijó']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 18, 'nome' => 'Armamar']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 19, 'nome' => 'Calheta (Madeira)']);
        DB::table('concelhos')->insert(['distrito_id' => 32, 'id' => 20, 'nome' => 'Porto Santo']);
        DB::table('concelhos')->insert(['distrito_id' => 41, 'id' => 21, 'nome' => 'Vila do Porto']);
        DB::table('concelhos')->insert(['distrito_id' => 42, 'id' => 22, 'nome' => 'Lagoa (São Miguel)']);
        DB::table('concelhos')->insert(['distrito_id' => 43, 'id' => 23, 'nome' => 'Angra do Heroísmo']);
        DB::table('concelhos')->insert(['distrito_id' => 44, 'id' => 24, 'nome' => 'Santa Cruz da Graciosa']);
        DB::table('concelhos')->insert(['distrito_id' => 45, 'id' => 25, 'nome' => 'Calheta (São Jorge)']);
        DB::table('concelhos')->insert(['distrito_id' => 46, 'id' => 26, 'nome' => 'Lajes do Pico']);
        DB::table('concelhos')->insert(['distrito_id' => 47, 'id' => 27, 'nome' => 'Horta']);
        DB::table('concelhos')->insert(['distrito_id' => 48, 'id' => 28, 'nome' => 'Lajes das Flores']);
        DB::table('concelhos')->insert(['distrito_id' => 49, 'id' => 29, 'nome' => 'Corvo']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 30, 'nome' => 'Albergaria-a-Velha']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 31, 'nome' => 'Almodôvar']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 32, 'nome' => 'Barcelos']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 33, 'nome' => 'Bragança']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 34, 'nome' => 'Castelo Branco']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 35, 'nome' => 'Cantanhede']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 36, 'nome' => 'Arraiolos']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 37, 'nome' => 'Alcoutim']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 38, 'nome' => 'Almeida']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 39, 'nome' => 'Alvaiázere']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 40, 'nome' => 'Arruda dos Vinhos']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 41, 'nome' => 'Arronches']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 42, 'nome' => 'Baião']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 43, 'nome' => 'Alcanena']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 44, 'nome' => 'Alcochete']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 45, 'nome' => 'Caminha']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 46, 'nome' => 'Boticas']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 47, 'nome' => 'Carregal do Sal']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 48, 'nome' => 'Câmara de Lobos']);
        DB::table('concelhos')->insert(['distrito_id' => 42, 'id' => 49, 'nome' => 'Nordeste']);
        DB::table('concelhos')->insert(['distrito_id' => 43, 'id' => 50, 'nome' => 'Praia da Vitória']);
        DB::table('concelhos')->insert(['distrito_id' => 45, 'id' => 51, 'nome' => 'Velas']);
        DB::table('concelhos')->insert(['distrito_id' => 46, 'id' => 52, 'nome' => 'Madalena']);
        DB::table('concelhos')->insert(['distrito_id' => 48, 'id' => 53, 'nome' => 'Santa Cruz das Flores']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 54, 'nome' => 'Anadia']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 55, 'nome' => 'Alvito']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 56, 'nome' => 'Braga']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 57, 'nome' => 'Carrazeda de Ansiães']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 58, 'nome' => 'Covilhã']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 59, 'nome' => 'Coimbra']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 60, 'nome' => 'Borba']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 61, 'nome' => 'Aljezur']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 62, 'nome' => 'Celorico da Beira']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 63, 'nome' => 'Ansião']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 64, 'nome' => 'Azambuja']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 65, 'nome' => 'Avis']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 66, 'nome' => 'Felgueiras']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 67, 'nome' => 'Almeirim']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 68, 'nome' => 'Almada']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 69, 'nome' => 'Melgaço']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 70, 'nome' => 'Chaves']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 71, 'nome' => 'Castro Daire']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 72, 'nome' => 'Funchal']);
        DB::table('concelhos')->insert(['distrito_id' => 42, 'id' => 73, 'nome' => 'Ponta Delgada']);
        DB::table('concelhos')->insert(['distrito_id' => 46, 'id' => 74, 'nome' => 'São Roque do Pico']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 75, 'nome' => 'Arouca']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 76, 'nome' => 'Barrancos']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 77, 'nome' => 'Cabeceiras de Basto']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 78, 'nome' => 'Freixo de Espada à Cinta']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 79, 'nome' => 'Fundão']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 80, 'nome' => 'Condeixa-a-Nova']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 81, 'nome' => 'Estremoz']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 82, 'nome' => 'Castro Marim']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 83, 'nome' => 'Figueira de Castelo Rodrigo']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 84, 'nome' => 'Batalha']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 85, 'nome' => 'Cadaval']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 86, 'nome' => 'Campo Maior']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 87, 'nome' => 'Gondomar']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 88, 'nome' => 'Alpiarça']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 89, 'nome' => 'Barreiro']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 90, 'nome' => 'Monção']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 91, 'nome' => 'Mesão Frio']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 92, 'nome' => 'Cinfães']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 93, 'nome' => 'Machico']);
        DB::table('concelhos')->insert(['distrito_id' => 42, 'id' => 94, 'nome' => 'Povoação']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 95, 'nome' => 'Aveiro']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 96, 'nome' => 'Beja']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 97, 'nome' => 'Celorico de Basto']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 98, 'nome' => 'Macedo de Cavaleiros']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 99, 'nome' => 'Idanha-a-Nova']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 100, 'nome' => 'Figueira da Foz']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 101, 'nome' => 'Évora']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 102, 'nome' => 'Faro']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 103, 'nome' => 'Fornos de Algodres']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 104, 'nome' => 'Bombarral']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 105, 'nome' => 'Cascais']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 106, 'nome' => 'Castelo de Vide']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 107, 'nome' => 'Lousada']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 108, 'nome' => 'Benavente']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 109, 'nome' => 'Grândola']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 110, 'nome' => 'Paredes de Coura']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 111, 'nome' => 'Mondim de Basto']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 112, 'nome' => 'Lamego']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 113, 'nome' => 'Ponta do Sol']);
        DB::table('concelhos')->insert(['distrito_id' => 42, 'id' => 114, 'nome' => 'Ribeira Grande']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 115, 'nome' => 'Castelo de Paiva']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 116, 'nome' => 'Castro Verde']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 117, 'nome' => 'Esposende']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 118, 'nome' => 'Miranda do Douro']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 119, 'nome' => 'Oleiros']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 120, 'nome' => 'Góis']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 121, 'nome' => 'Montemor-o-Novo']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 122, 'nome' => 'Lagoa (Algarve)']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 123, 'nome' => 'Gouveia']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 124, 'nome' => 'Caldas da Rainha']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 125, 'nome' => 'Lisboa']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 126, 'nome' => 'Crato']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 127, 'nome' => 'Maia']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 128, 'nome' => 'Cartaxo']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 129, 'nome' => 'Moita']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 130, 'nome' => 'Ponte da Barca']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 131, 'nome' => 'Montalegre']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 132, 'nome' => 'Mangualde']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 133, 'nome' => 'Porto Moniz']);
        DB::table('concelhos')->insert(['distrito_id' => 42, 'id' => 134, 'nome' => 'Vila Franca do Campo']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 135, 'nome' => 'Espinho']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 136, 'nome' => 'Cuba']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 137, 'nome' => 'Fafe']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 138, 'nome' => 'Mirandela']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 139, 'nome' => 'Penamacor']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 140, 'nome' => 'Lousã']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 141, 'nome' => 'Mora']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 142, 'nome' => 'Lagos']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 143, 'nome' => 'Guarda']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 144, 'nome' => 'Castanheira de Pêra']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 145, 'nome' => 'Loures']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 146, 'nome' => 'Elvas']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 147, 'nome' => 'Marco de Canaveses']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 148, 'nome' => 'Chamusca']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 149, 'nome' => 'Montijo']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 150, 'nome' => 'Ponte de Lima']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 151, 'nome' => 'Murça']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 152, 'nome' => 'Moimenta da Beira']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 153, 'nome' => 'Ribeira Brava']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 154, 'nome' => 'Estarreja']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 155, 'nome' => 'Ferreira do Alentejo']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 156, 'nome' => 'Guimarães']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 157, 'nome' => 'Mogadouro']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 158, 'nome' => 'Proença-a-Nova']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 159, 'nome' => 'Mira']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 160, 'nome' => 'Mourão']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 161, 'nome' => 'Loulé']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 162, 'nome' => 'Manteigas']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 163, 'nome' => 'Figueiró dos Vinhos']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 164, 'nome' => 'Lourinhã']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 165, 'nome' => 'Fronteira']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 166, 'nome' => 'Matosinhos']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 167, 'nome' => 'Constância']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 168, 'nome' => 'Palmela']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 169, 'nome' => 'Valença']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 170, 'nome' => 'Peso da Régua']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 171, 'nome' => 'Mortágua']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 172, 'nome' => 'Santa Cruz']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 173, 'nome' => 'Santa Maria da Feira']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 174, 'nome' => 'Mértola']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 175, 'nome' => 'Póvoa de Lanhoso']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 176, 'nome' => 'Torre de Moncorvo']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 177, 'nome' => 'Sertã']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 178, 'nome' => 'Miranda do Corvo']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 179, 'nome' => 'Portel']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 180, 'nome' => 'Monchique']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 181, 'nome' => 'Meda']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 182, 'nome' => 'Leiria']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 183, 'nome' => 'Mafra']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 184, 'nome' => 'Gavião']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 185, 'nome' => 'Paços de Ferreira']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 186, 'nome' => 'Coruche']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 187, 'nome' => 'Santiago do Cacém']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 188, 'nome' => 'Viana do Castelo']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 189, 'nome' => 'Ribeira de Pena']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 190, 'nome' => 'Nelas']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 191, 'nome' => 'Santana']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 192, 'nome' => 'Ílhavo']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 193, 'nome' => 'Moura']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 194, 'nome' => 'Terras de Bouro']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 195, 'nome' => 'Vila Flor']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 196, 'nome' => 'Vila de Rei']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 197, 'nome' => 'Montemor-o-Velho']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 198, 'nome' => 'Redondo']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 199, 'nome' => 'Olhão']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 200, 'nome' => 'Pinhel']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 201, 'nome' => 'Marinha Grande']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 202, 'nome' => 'Oeiras']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 203, 'nome' => 'Marvão']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 204, 'nome' => 'Paredes']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 205, 'nome' => 'Entroncamento']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 206, 'nome' => 'Seixal']);
        DB::table('concelhos')->insert(['distrito_id' => 16, 'id' => 207, 'nome' => 'Vila Nova de Cerveira']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 208, 'nome' => 'Sabrosa']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 209, 'nome' => 'Oliveira de Frades']);
        DB::table('concelhos')->insert(['distrito_id' => 31, 'id' => 210, 'nome' => 'São Vicente']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 211, 'nome' => 'Mealhada']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 212, 'nome' => 'Odemira']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 213, 'nome' => 'Vieira do Minho']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 214, 'nome' => 'Vimioso']);
        DB::table('concelhos')->insert(['distrito_id' => 5, 'id' => 215, 'nome' => 'Vila Velha de Ródão']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 216, 'nome' => 'Oliveira do Hospital']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 217, 'nome' => 'Reguengos de Monsaraz']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 218, 'nome' => 'Portimão']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 219, 'nome' => 'Sabugal']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 220, 'nome' => 'Nazaré']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 221, 'nome' => 'Sintra']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 222, 'nome' => 'Monforte']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 223, 'nome' => 'Penafiel']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 224, 'nome' => 'Ferreira do Zêzere']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 225, 'nome' => 'Sesimbra']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 226, 'nome' => 'Santa Marta de Penaguião']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 227, 'nome' => 'Penalva do Castelo']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 228, 'nome' => 'Murtosa']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 229, 'nome' => 'Ourique']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 230, 'nome' => 'Vila Nova de Famalicão']);
        DB::table('concelhos')->insert(['distrito_id' => 4, 'id' => 231, 'nome' => 'Vinhais']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 232, 'nome' => 'Pampilhosa da Serra']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 233, 'nome' => 'Vendas Novas']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 234, 'nome' => 'São Brás de Alportel']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 235, 'nome' => 'Seia']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 236, 'nome' => 'Óbidos']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 237, 'nome' => 'Sobral de Monte Agraço']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 238, 'nome' => 'Nisa']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 239, 'nome' => 'Porto']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 240, 'nome' => 'Golegã']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 241, 'nome' => 'Setúbal']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 242, 'nome' => 'Valpaços']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 243, 'nome' => 'Penedono']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 244, 'nome' => 'Oliveira de Azeméis']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 245, 'nome' => 'Serpa']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 246, 'nome' => 'Vila Verde']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 247, 'nome' => 'Penacova']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 248, 'nome' => 'Viana do Alentejo']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 249, 'nome' => 'Silves']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 250, 'nome' => 'Trancoso']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 251, 'nome' => 'Pedrógão Grande']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 252, 'nome' => 'Torres Vedras']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 253, 'nome' => 'Ponte de Sor']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 254, 'nome' => 'Póvoa de Varzim']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 255, 'nome' => 'Mação']);
        DB::table('concelhos')->insert(['distrito_id' => 15, 'id' => 256, 'nome' => 'Sines']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 257, 'nome' => 'Vila Pouca de Aguiar']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 258, 'nome' => 'Resende']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 259, 'nome' => 'Oliveira do Bairro']);
        DB::table('concelhos')->insert(['distrito_id' => 2, 'id' => 260, 'nome' => 'Vidigueira']);
        DB::table('concelhos')->insert(['distrito_id' => 3, 'id' => 261, 'nome' => 'Vizela']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 262, 'nome' => 'Penela']);
        DB::table('concelhos')->insert(['distrito_id' => 7, 'id' => 263, 'nome' => 'Vila Viçosa']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 264, 'nome' => 'Tavira']);
        DB::table('concelhos')->insert(['distrito_id' => 9, 'id' => 265, 'nome' => 'Vila Nova de Foz Côa']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 266, 'nome' => 'Peniche']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 267, 'nome' => 'Vila Franca de Xira']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 268, 'nome' => 'Portalegre']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 269, 'nome' => 'Santo Tirso']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 270, 'nome' => 'Rio Maior']);
        DB::table('concelhos')->insert(['distrito_id' => 17, 'id' => 271, 'nome' => 'Vila Real']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 272, 'nome' => 'Santa Comba Dão']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 273, 'nome' => 'Ovar']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 274, 'nome' => 'Soure']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 275, 'nome' => 'Vila do Bispo']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 276, 'nome' => 'Pombal']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 277, 'nome' => 'Amadora']);
        DB::table('concelhos')->insert(['distrito_id' => 12, 'id' => 278, 'nome' => 'Sousel']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 279, 'nome' => 'Valongo']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 280, 'nome' => 'Salvaterra de Magos']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 281, 'nome' => 'São João da Pesqueira']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 282, 'nome' => 'São João da Madeira']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 283, 'nome' => 'Tábua']);
        DB::table('concelhos')->insert(['distrito_id' => 8, 'id' => 284, 'nome' => 'Vila Real de Santo António']);
        DB::table('concelhos')->insert(['distrito_id' => 10, 'id' => 285, 'nome' => 'Porto de Mós']);
        DB::table('concelhos')->insert(['distrito_id' => 11, 'id' => 286, 'nome' => 'Odivelas']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 287, 'nome' => 'Vila do Conde']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 288, 'nome' => 'Santarém']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 289, 'nome' => 'São Pedro do Sul']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 290, 'nome' => 'Sever do Vouga']);
        DB::table('concelhos')->insert(['distrito_id' => 6, 'id' => 291, 'nome' => 'Vila Nova de Poiares']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 292, 'nome' => 'Vila Nova de Gaia']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 293, 'nome' => 'Sardoal']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 294, 'nome' => 'Sátão']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 295, 'nome' => 'Vagos']);
        DB::table('concelhos')->insert(['distrito_id' => 13, 'id' => 296, 'nome' => 'Trofa']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 297, 'nome' => 'Tomar']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 298, 'nome' => 'Sernancelhe']);
        DB::table('concelhos')->insert(['distrito_id' => 1, 'id' => 299, 'nome' => 'Vale de Cambra']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 300, 'nome' => 'Torres Novas']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 301, 'nome' => 'Tabuaço']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 302, 'nome' => 'Vila Nova da Barquinha']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 303, 'nome' => 'Tarouca']);
        DB::table('concelhos')->insert(['distrito_id' => 14, 'id' => 304, 'nome' => 'Ourém']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 305, 'nome' => 'Tondela']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 306, 'nome' => 'Vila Nova de Paiva']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 307, 'nome' => 'Viseu']);
        DB::table('concelhos')->insert(['distrito_id' => 18, 'id' => 308, 'nome' => 'Vouzela']);
    }
}
