const concelhos = [
    { distrito_id: 1, id: 1, nome: 'Águeda' },
    { distrito_id: 2, id: 1, nome: 'Aljustrel' },
    { distrito_id: 3, id: 1, nome: 'Amares' },
    { distrito_id: 4, id: 1, nome: 'Alfândega da Fé' },
    { distrito_id: 5, id: 1, nome: 'Belmonte' },
    { distrito_id: 6, id: 1, nome: 'Arganil' },
    { distrito_id: 7, id: 1, nome: 'Alandroal' },
    { distrito_id: 8, id: 1, nome: 'Albufeira' },
    { distrito_id: 9, id: 1, nome: 'Aguiar da Beira' },
    { distrito_id: 10, id: 1, nome: 'Alcobaça' },
    { distrito_id: 11, id: 1, nome: 'Alenquer' },
    { distrito_id: 12, id: 1, nome: 'Alter do Chão' },
    { distrito_id: 13, id: 1, nome: 'Amarante' },
    { distrito_id: 14, id: 1, nome: 'Abrantes' },
    { distrito_id: 15, id: 1, nome: 'Alcácer do Sal' },
    { distrito_id: 16, id: 1, nome: 'Arcos de Valdevez' },
    { distrito_id: 17, id: 1, nome: 'Alijó' },
    { distrito_id: 18, id: 1, nome: 'Armamar' },
    { distrito_id: 31, id: 1, nome: 'Calheta (Madeira)' },
    { distrito_id: 32, id: 1, nome: 'Porto Santo' },
    { distrito_id: 41, id: 1, nome: 'Vila do Porto' },
    { distrito_id: 42, id: 1, nome: 'Lagoa (São Miguel)' },
    { distrito_id: 43, id: 1, nome: 'Angra do Heroísmo' },
    { distrito_id: 44, id: 1, nome: 'Santa Cruz da Graciosa' },
    { distrito_id: 45, id: 1, nome: 'Calheta (São Jorge)' },
    { distrito_id: 46, id: 1, nome: 'Lajes do Pico' },
    { distrito_id: 47, id: 1, nome: 'Horta' },
    { distrito_id: 48, id: 1, nome: 'Lajes das Flores' },
    { distrito_id: 49, id: 1, nome: 'Corvo' },
    { distrito_id: 1, id: 2, nome: 'Albergaria-a-Velha' },
    { distrito_id: 2, id: 2, nome: 'Almodôvar' },
    { distrito_id: 3, id: 2, nome: 'Barcelos' },
    { distrito_id: 4, id: 2, nome: 'Bragança' },
    { distrito_id: 5, id: 2, nome: 'Castelo Branco' },
    { distrito_id: 6, id: 2, nome: 'Cantanhede' },
    { distrito_id: 7, id: 2, nome: 'Arraiolos' },
    { distrito_id: 8, id: 2, nome: 'Alcoutim' },
    { distrito_id: 9, id: 2, nome: 'Almeida' },
    { distrito_id: 10, id: 2, nome: 'Alvaiázere' },
    { distrito_id: 11, id: 2, nome: 'Arruda dos Vinhos' },
    { distrito_id: 12, id: 2, nome: 'Arronches' },
    { distrito_id: 13, id: 2, nome: 'Baião' },
    { distrito_id: 14, id: 2, nome: 'Alcanena' },
    { distrito_id: 15, id: 2, nome: 'Alcochete' },
    { distrito_id: 16, id: 2, nome: 'Caminha' },
    { distrito_id: 17, id: 2, nome: 'Boticas' },
    { distrito_id: 18, id: 2, nome: 'Carregal do Sal' },
    { distrito_id: 31, id: 2, nome: 'Câmara de Lobos' },
    { distrito_id: 42, id: 2, nome: 'Nordeste' },
    { distrito_id: 43, id: 2, nome: 'Praia da Vitória' },
    { distrito_id: 45, id: 2, nome: 'Velas' },
    { distrito_id: 46, id: 2, nome: 'Madalena' },
    { distrito_id: 48, id: 2, nome: 'Santa Cruz das Flores' },
    { distrito_id: 1, id: 3, nome: 'Anadia' },
    { distrito_id: 2, id: 3, nome: 'Alvito' },
    { distrito_id: 3, id: 3, nome: 'Braga' },
    { distrito_id: 4, id: 3, nome: 'Carrazeda de Ansiães' },
    { distrito_id: 5, id: 3, nome: 'Covilhã' },
    { distrito_id: 6, id: 3, nome: 'Coimbra' },
    { distrito_id: 7, id: 3, nome: 'Borba' },
    { distrito_id: 8, id: 3, nome: 'Aljezur' },
    { distrito_id: 9, id: 3, nome: 'Celorico da Beira' },
    { distrito_id: 10, id: 3, nome: 'Ansião' },
    { distrito_id: 11, id: 3, nome: 'Azambuja' },
    { distrito_id: 12, id: 3, nome: 'Avis' },
    { distrito_id: 13, id: 3, nome: 'Felgueiras' },
    { distrito_id: 14, id: 3, nome: 'Almeirim' },
    { distrito_id: 15, id: 3, nome: 'Almada' },
    { distrito_id: 16, id: 3, nome: 'Melgaço' },
    { distrito_id: 17, id: 3, nome: 'Chaves' },
    { distrito_id: 18, id: 3, nome: 'Castro Daire' },
    { distrito_id: 31, id: 3, nome: 'Funchal' },
    { distrito_id: 42, id: 3, nome: 'Ponta Delgada' },
    { distrito_id: 46, id: 3, nome: 'São Roque do Pico' },
    { distrito_id: 1, id: 4, nome: 'Arouca' },
    { distrito_id: 2, id: 4, nome: 'Barrancos' },
    { distrito_id: 3, id: 4, nome: 'Cabeceiras de Basto' },
    { distrito_id: 4, id: 4, nome: 'Freixo de Espada à Cinta' },
    { distrito_id: 5, id: 4, nome: 'Fundão' },
    { distrito_id: 6, id: 4, nome: 'Condeixa-a-Nova' },
    { distrito_id: 7, id: 4, nome: 'Estremoz' },
    { distrito_id: 8, id: 4, nome: 'Castro Marim' },
    { distrito_id: 9, id: 4, nome: 'Figueira de Castelo Rodrigo' },
    { distrito_id: 10, id: 4, nome: 'Batalha' },
    { distrito_id: 11, id: 4, nome: 'Cadaval' },
    { distrito_id: 12, id: 4, nome: 'Campo Maior' },
    { distrito_id: 13, id: 4, nome: 'Gondomar' },
    { distrito_id: 14, id: 4, nome: 'Alpiarça' },
    { distrito_id: 15, id: 4, nome: 'Barreiro' },
    { distrito_id: 16, id: 4, nome: 'Monção' },
    { distrito_id: 17, id: 4, nome: 'Mesão Frio' },
    { distrito_id: 18, id: 4, nome: 'Cinfães' },
    { distrito_id: 31, id: 4, nome: 'Machico' },
    { distrito_id: 42, id: 4, nome: 'Povoação' },
    { distrito_id: 1, id: 5, nome: 'Aveiro' },
    { distrito_id: 2, id: 5, nome: 'Beja' },
    { distrito_id: 3, id: 5, nome: 'Celorico de Basto' },
    { distrito_id: 4, id: 5, nome: 'Macedo de Cavaleiros' },
    { distrito_id: 5, id: 5, nome: 'Idanha-a-Nova' },
    { distrito_id: 6, id: 5, nome: 'Figueira da Foz' },
    { distrito_id: 7, id: 5, nome: 'Évora' },
    { distrito_id: 8, id: 5, nome: 'Faro' },
    { distrito_id: 9, id: 5, nome: 'Fornos de Algodres' },
    { distrito_id: 10, id: 5, nome: 'Bombarral' },
    { distrito_id: 11, id: 5, nome: 'Cascais' },
    { distrito_id: 12, id: 5, nome: 'Castelo de Vide' },
    { distrito_id: 13, id: 5, nome: 'Lousada' },
    { distrito_id: 14, id: 5, nome: 'Benavente' },
    { distrito_id: 15, id: 5, nome: 'Grândola' },
    { distrito_id: 16, id: 5, nome: 'Paredes de Coura' },
    { distrito_id: 17, id: 5, nome: 'Mondim de Basto' },
    { distrito_id: 18, id: 5, nome: 'Lamego' },
    { distrito_id: 31, id: 5, nome: 'Ponta do Sol' },
    { distrito_id: 42, id: 5, nome: 'Ribeira Grande' },
    { distrito_id: 1, id: 6, nome: 'Castelo de Paiva' },
    { distrito_id: 2, id: 6, nome: 'Castro Verde' },
    { distrito_id: 3, id: 6, nome: 'Esposende' },
    { distrito_id: 4, id: 6, nome: 'Miranda do Douro' },
    { distrito_id: 5, id: 6, nome: 'Oleiros' },
    { distrito_id: 6, id: 6, nome: 'Góis' },
    { distrito_id: 7, id: 6, nome: 'Montemor-o-Novo' },
    { distrito_id: 8, id: 6, nome: 'Lagoa (Algarve)' },
    { distrito_id: 9, id: 6, nome: 'Gouveia' },
    { distrito_id: 10, id: 6, nome: 'Caldas da Rainha' },
    { distrito_id: 11, id: 6, nome: 'Lisboa' },
    { distrito_id: 12, id: 6, nome: 'Crato' },
    { distrito_id: 13, id: 6, nome: 'Maia' },
    { distrito_id: 14, id: 6, nome: 'Cartaxo' },
    { distrito_id: 15, id: 6, nome: 'Moita' },
    { distrito_id: 16, id: 6, nome: 'Ponte da Barca' },
    { distrito_id: 17, id: 6, nome: 'Montalegre' },
    { distrito_id: 18, id: 6, nome: 'Mangualde' },
    { distrito_id: 31, id: 6, nome: 'Porto Moniz' },
    { distrito_id: 42, id: 6, nome: 'Vila Franca do Campo' },
    { distrito_id: 1, id: 7, nome: 'Espinho' },
    { distrito_id: 2, id: 7, nome: 'Cuba' },
    { distrito_id: 3, id: 7, nome: 'Fafe' },
    { distrito_id: 4, id: 7, nome: 'Mirandela' },
    { distrito_id: 5, id: 7, nome: 'Penamacor' },
    { distrito_id: 6, id: 7, nome: 'Lousã' },
    { distrito_id: 7, id: 7, nome: 'Mora' },
    { distrito_id: 8, id: 7, nome: 'Lagos' },
    { distrito_id: 9, id: 7, nome: 'Guarda' },
    { distrito_id: 10, id: 7, nome: 'Castanheira de Pêra' },
    { distrito_id: 11, id: 7, nome: 'Loures' },
    { distrito_id: 12, id: 7, nome: 'Elvas' },
    { distrito_id: 13, id: 7, nome: 'Marco de Canaveses' },
    { distrito_id: 14, id: 7, nome: 'Chamusca' },
    { distrito_id: 15, id: 7, nome: 'Montijo' },
    { distrito_id: 16, id: 7, nome: 'Ponte de Lima' },
    { distrito_id: 17, id: 7, nome: 'Murça' },
    { distrito_id: 18, id: 7, nome: 'Moimenta da Beira' },
    { distrito_id: 31, id: 7, nome: 'Ribeira Brava' },
    { distrito_id: 1, id: 8, nome: 'Estarreja' },
    { distrito_id: 2, id: 8, nome: 'Ferreira do Alentejo' },
    { distrito_id: 3, id: 8, nome: 'Guimarães' },
    { distrito_id: 4, id: 8, nome: 'Mogadouro' },
    { distrito_id: 5, id: 8, nome: 'Proença-a-Nova' },
    { distrito_id: 6, id: 8, nome: 'Mira' },
    { distrito_id: 7, id: 8, nome: 'Mourão' },
    { distrito_id: 8, id: 8, nome: 'Loulé' },
    { distrito_id: 9, id: 8, nome: 'Manteigas' },
    { distrito_id: 10, id: 8, nome: 'Figueiró dos Vinhos' },
    { distrito_id: 11, id: 8, nome: 'Lourinhã' },
    { distrito_id: 12, id: 8, nome: 'Fronteira' },
    { distrito_id: 13, id: 8, nome: 'Matosinhos' },
    { distrito_id: 14, id: 8, nome: 'Constância' },
    { distrito_id: 15, id: 8, nome: 'Palmela' },
    { distrito_id: 16, id: 8, nome: 'Valença' },
    { distrito_id: 17, id: 8, nome: 'Peso da Régua' },
    { distrito_id: 18, id: 8, nome: 'Mortágua' },
    { distrito_id: 31, id: 8, nome: 'Santa Cruz' },
    { distrito_id: 1, id: 9, nome: 'Santa Maria da Feira' },
    { distrito_id: 2, id: 9, nome: 'Mértola' },
    { distrito_id: 3, id: 9, nome: 'Póvoa de Lanhoso' },
    { distrito_id: 4, id: 9, nome: 'Torre de Moncorvo' },
    { distrito_id: 5, id: 9, nome: 'Sertã' },
    { distrito_id: 6, id: 9, nome: 'Miranda do Corvo' },
    { distrito_id: 7, id: 9, nome: 'Portel' },
    { distrito_id: 8, id: 9, nome: 'Monchique' },
    { distrito_id: 9, id: 9, nome: 'Meda' },
    { distrito_id: 10, id: 9, nome: 'Leiria' },
    { distrito_id: 11, id: 9, nome: 'Mafra' },
    { distrito_id: 12, id: 9, nome: 'Gavião' },
    { distrito_id: 13, id: 9, nome: 'Paços de Ferreira' },
    { distrito_id: 14, id: 9, nome: 'Coruche' },
    { distrito_id: 15, id: 9, nome: 'Santiago do Cacém' },
    { distrito_id: 16, id: 9, nome: 'Viana do Castelo' },
    { distrito_id: 17, id: 9, nome: 'Ribeira de Pena' },
    { distrito_id: 18, id: 9, nome: 'Nelas' },
    { distrito_id: 31, id: 9, nome: 'Santana' },
    { distrito_id: 1, id: 10, nome: 'Ílhavo' },
    { distrito_id: 2, id: 10, nome: 'Moura' },
    { distrito_id: 3, id: 10, nome: 'Terras de Bouro' },
    { distrito_id: 4, id: 10, nome: 'Vila Flor' },
    { distrito_id: 5, id: 10, nome: 'Vila de Rei' },
    { distrito_id: 6, id: 10, nome: 'Montemor-o-Velho' },
    { distrito_id: 7, id: 10, nome: 'Redondo' },
    { distrito_id: 8, id: 10, nome: 'Olhão' },
    { distrito_id: 9, id: 10, nome: 'Pinhel' },
    { distrito_id: 10, id: 10, nome: 'Marinha Grande' },
    { distrito_id: 11, id: 10, nome: 'Oeiras' },
    { distrito_id: 12, id: 10, nome: 'Marvão' },
    { distrito_id: 13, id: 10, nome: 'Paredes' },
    { distrito_id: 14, id: 10, nome: 'Entroncamento' },
    { distrito_id: 15, id: 10, nome: 'Seixal' },
    { distrito_id: 16, id: 10, nome: 'Vila Nova de Cerveira' },
    { distrito_id: 17, id: 10, nome: 'Sabrosa' },
    { distrito_id: 18, id: 10, nome: 'Oliveira de Frades' },
    { distrito_id: 31, id: 10, nome: 'São Vicente' },
    { distrito_id: 1, id: 11, nome: 'Mealhada' },
    { distrito_id: 2, id: 11, nome: 'Odemira' },
    { distrito_id: 3, id: 11, nome: 'Vieira do Minho' },
    { distrito_id: 4, id: 11, nome: 'Vimioso' },
    { distrito_id: 5, id: 11, nome: 'Vila Velha de Ródão' },
    { distrito_id: 6, id: 11, nome: 'Oliveira do Hospital' },
    { distrito_id: 7, id: 11, nome: 'Reguengos de Monsaraz' },
    { distrito_id: 8, id: 11, nome: 'Portimão' },
    { distrito_id: 9, id: 11, nome: 'Sabugal' },
    { distrito_id: 10, id: 11, nome: 'Nazaré' },
    { distrito_id: 11, id: 11, nome: 'Sintra' },
    { distrito_id: 12, id: 11, nome: 'Monforte' },
    { distrito_id: 13, id: 11, nome: 'Penafiel' },
    { distrito_id: 14, id: 11, nome: 'Ferreira do Zêzere' },
    { distrito_id: 15, id: 11, nome: 'Sesimbra' },
    { distrito_id: 17, id: 11, nome: 'Santa Marta de Penaguião' },
    { distrito_id: 18, id: 11, nome: 'Penalva do Castelo' },
    { distrito_id: 1, id: 12, nome: 'Murtosa' },
    { distrito_id: 2, id: 12, nome: 'Ourique' },
    { distrito_id: 3, id: 12, nome: 'Vila Nova de Famalicão' },
    { distrito_id: 4, id: 12, nome: 'Vinhais' },
    { distrito_id: 6, id: 12, nome: 'Pampilhosa da Serra' },
    { distrito_id: 7, id: 12, nome: 'Vendas Novas' },
    { distrito_id: 8, id: 12, nome: 'São Brás de Alportel' },
    { distrito_id: 9, id: 12, nome: 'Seia' },
    { distrito_id: 10, id: 12, nome: 'Óbidos' },
    { distrito_id: 11, id: 12, nome: 'Sobral de Monte Agraço' },
    { distrito_id: 12, id: 12, nome: 'Nisa' },
    { distrito_id: 13, id: 12, nome: 'Porto' },
    { distrito_id: 14, id: 12, nome: 'Golegã' },
    { distrito_id: 15, id: 12, nome: 'Setúbal' },
    { distrito_id: 17, id: 12, nome: 'Valpaços' },
    { distrito_id: 18, id: 12, nome: 'Penedono' },
    { distrito_id: 1, id: 13, nome: 'Oliveira de Azeméis' },
    { distrito_id: 2, id: 13, nome: 'Serpa' },
    { distrito_id: 3, id: 13, nome: 'Vila Verde' },
    { distrito_id: 6, id: 13, nome: 'Penacova' },
    { distrito_id: 7, id: 13, nome: 'Viana do Alentejo' },
    { distrito_id: 8, id: 13, nome: 'Silves' },
    { distrito_id: 9, id: 13, nome: 'Trancoso' },
    { distrito_id: 10, id: 13, nome: 'Pedrógão Grande' },
    { distrito_id: 11, id: 13, nome: 'Torres Vedras' },
    { distrito_id: 12, id: 13, nome: 'Ponte de Sor' },
    { distrito_id: 13, id: 13, nome: 'Póvoa de Varzim' },
    { distrito_id: 14, id: 13, nome: 'Mação' },
    { distrito_id: 15, id: 13, nome: 'Sines' },
    { distrito_id: 17, id: 13, nome: 'Vila Pouca de Aguiar' },
    { distrito_id: 18, id: 13, nome: 'Resende' },
    { distrito_id: 1, id: 14, nome: 'Oliveira do Bairro' },
    { distrito_id: 2, id: 14, nome: 'Vidigueira' },
    { distrito_id: 3, id: 14, nome: 'Vizela' },
    { distrito_id: 6, id: 14, nome: 'Penela' },
    { distrito_id: 7, id: 14, nome: 'Vila Viçosa' },
    { distrito_id: 8, id: 14, nome: 'Tavira' },
    { distrito_id: 9, id: 14, nome: 'Vila Nova de Foz Côa' },
    { distrito_id: 10, id: 14, nome: 'Peniche' },
    { distrito_id: 11, id: 14, nome: 'Vila Franca de Xira' },
    { distrito_id: 12, id: 14, nome: 'Portalegre' },
    { distrito_id: 13, id: 14, nome: 'Santo Tirso' },
    { distrito_id: 14, id: 14, nome: 'Rio Maior' },
    { distrito_id: 17, id: 14, nome: 'Vila Real' },
    { distrito_id: 18, id: 14, nome: 'Santa Comba Dão' },
    { distrito_id: 1, id: 15, nome: 'Ovar' },
    { distrito_id: 6, id: 15, nome: 'Soure' },
    { distrito_id: 8, id: 15, nome: 'Vila do Bispo' },
    { distrito_id: 10, id: 15, nome: 'Pombal' },
    { distrito_id: 11, id: 15, nome: 'Amadora' },
    { distrito_id: 12, id: 15, nome: 'Sousel' },
    { distrito_id: 13, id: 15, nome: 'Valongo' },
    { distrito_id: 14, id: 15, nome: 'Salvaterra de Magos' },
    { distrito_id: 18, id: 15, nome: 'São João da Pesqueira' },
    { distrito_id: 1, id: 16, nome: 'São João da Madeira' },
    { distrito_id: 6, id: 16, nome: 'Tábua' },
    { distrito_id: 8, id: 16, nome: 'Vila Real de Santo António' },
    { distrito_id: 10, id: 16, nome: 'Porto de Mós' },
    { distrito_id: 11, id: 16, nome: 'Odivelas' },
    { distrito_id: 13, id: 16, nome: 'Vila do Conde' },
    { distrito_id: 14, id: 16, nome: 'Santarém' },
    { distrito_id: 18, id: 16, nome: 'São Pedro do Sul' },
    { distrito_id: 1, id: 17, nome: 'Sever do Vouga' },
    { distrito_id: 6, id: 17, nome: 'Vila Nova de Poiares' },
    { distrito_id: 13, id: 17, nome: 'Vila Nova de Gaia' },
    { distrito_id: 14, id: 17, nome: 'Sardoal' },
    { distrito_id: 18, id: 17, nome: 'Sátão' },
    { distrito_id: 1, id: 18, nome: 'Vagos' },
    { distrito_id: 13, id: 18, nome: 'Trofa' },
    { distrito_id: 14, id: 18, nome: 'Tomar' },
    { distrito_id: 18, id: 18, nome: 'Sernancelhe' },
    { distrito_id: 1, id: 19, nome: 'Vale de Cambra' },
    { distrito_id: 14, id: 19, nome: 'Torres Novas' },
    { distrito_id: 18, id: 19, nome: 'Tabuaço' },
    { distrito_id: 14, id: 20, nome: 'Vila Nova da Barquinha' },
    { distrito_id: 18, id: 20, nome: 'Tarouca' },
    { distrito_id: 14, id: 21, nome: 'Ourém' },
    { distrito_id: 18, id: 21, nome: 'Tondela' },
    { distrito_id: 18, id: 22, nome: 'Vila Nova de Paiva' },
    { distrito_id: 18, id: 23, nome: 'Viseu' },
    { distrito_id: 18, id: 24, nome: 'Vouzela' },
]

export default concelhos
