const distritos = [
    { id: 1, nome: "Aveiro" },
    { id: 2, nome: "Beja" },
    { id: 3, nome: "Braga" },
    { id: 4, nome: "Bragança" },
    { id: 5, nome: "Castelo Branco" },
    { id: 6, nome: "Coimbra" },
    { id: 7, nome: "Évora" },
    { id: 8, nome: "Faro" },
    { id: 9, nome: "Guarda" },
    { id: 10, nome: "Leiria" },
    { id: 11, nome: "Lisboa" },
    { id: 12, nome: "Portalegre" },
    { id: 13, nome: "Porto" },
    { id: 14, nome: "Santarém" },
    { id: 15, nome: "Setúbal" },
    { id: 16, nome: "Viana do Castelo" },
    { id: 17, nome: "Vila Real" },
    { id: 18, nome: "Viseu" },
    { id: 31, nome: "Ilha da Madeira" },
    { id: 32, nome: "Ilha de Porto Santo" },
    { id: 41, nome: "Ilha de Santa Maria" },
    { id: 42, nome: "Ilha de São Miguel" },
    { id: 43, nome: "Ilha Terceira" },
    { id: 44, nome: "Ilha da Graciosa" },
    { id: 45, nome: "Ilha de São Jorge" },
    { id: 46, nome: "Ilha do Pico" },
    { id: 47, nome: "Ilha do Faial" },
    { id: 48, nome: "Ilha das Flores" },
    { id: 49, nome: "Ilha do Corvo" },
]

export default distritos
